adonis:
  xconf:
    address: 

dubbo:
  registry:
    id: my-reg
    protocol: zookeeper
    address: localhost:2181
  #    register: false
  protocol:
    id: dubbo
    name: dubbo
    port: 20884

server:
  port: 8081
