adonis:
  xconf:
    address:
dubbo:
  registry:
    id: my-reg
    address: zookeeper://localhost:2181
#    register: false
  protocol:
    id: dubbo
    name: dubbo
    port: 20882

cas:
  clientHostUrl: http://192.168.1.190:8083/api
  serverHostUrl: http://testadmin1.gegejia.com/ygg-sso

front:
  serverUrl: http://192.168.1.190:8091/

platform_id: 48

