adonis:
  xconf:
    address: 
dubbo:
  registry:
    id: my-reg
    protocol: zookeeper
    address: 
  protocol:
    id: dubbo
    name: dubbo
    port: 20880

platform_id: 48

cas:
  clientHostUrl: http://center-bi.conf.test.gegejia.com/api
  serverHostUrl: http://testadmin1.gegejia.com/ygg-sso

front:
  serverUrl: http://center-bi.conf.test.gegejia.com/#/
