adonis:
  xconf:
    address: 

dubbo:
  registry:
    id: my-reg
    protocol: zookeeper
    address: 
  protocol:
    id: dubbo
    name: dubbo
    port: 20880

cas:
  clientHostUrl: http://47.99.225.89/api
  serverHostUrl: http://47.96.222.109/ygg-sso

front:
  serverUrl: http://47.99.225.89/#/

platform_id: 29
