adonis:
  xconf:
    address: 47.99.2.51:2181,47.99.2.51:2182,47.99.2.51:2183

#dubbo:
#  registry:
#    address: zookeeper://localhost:2181
dubbo:
  registry:
    id: my-reg
    protocol: zookeeper
    address: localhost:2181
#    register: false
  protocol:
    id: dubbo
    name: dubbo
    port: 20880



